In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
df = pickle.load(open('df','rb'))

In [3]:
backup = df

In [4]:
df=backup

In [5]:
df.head()

,innings,meta.data_version,meta.created,meta.revision,info.city,info.dates,info.gender,info.match_type,info.outcome.by.runs,info.outcome.winner,...,info.supersubs.Sri Lanka,info.supersubs.Bangladesh,info.supersubs.New Zealand,info.supersubs.India,info.supersubs.ICC World XI,info.supersubs.South Africa,info.supersubs.Pakistan,info.bowl_out,info.outcome.bowl_out,info.supersubs.West Indies
0,"[{'1st innings': {'team': 'South Africa', 'del...",0.9,2016-11-09,2,Perth,"[2016-11-03, 2016-11-04, 2016-11-05, 2016-11-0...",male,Test,177.0,South Africa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2016-11-16,2,Hobart,"[2016-11-12, 2016-11-13, 2016-11-14, 2016-11-15]",male,Test,80.0,South Africa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'South Africa', 'dec...",0.9,2016-12-05,1,NaN,"[2016-11-24, 2016-11-25, 2016-11-26, 2016-11-27]",male,Test,NaN,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2016-12-21,1,Brisbane,"[2016-12-15, 2016-12-16, 2016-12-17, 2016-12-1...",male,Test,39.0,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Pakistan', 'declare...",0.9,2016-12-31,1,NaN,"[2016-12-26, 2016-12-27, 2016-12-28, 2016-12-2...",male,Test,18.0,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.iloc[0]['innings'][0].keys()

dict_keys(['1st innings'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7470 entries, 0 to 7469
Data columns (total 45 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   innings                             7470 non-null   object
 1   meta.data_version                   7470 non-null   float64
 2   meta.created                        7470 non-null   object
 3   meta.revision                       7470 non-null   int64
 4   info.city                           6549 non-null   object
 5   info.dates                          7470 non-null   object
 6   info.gender                         7470 non-null   object
 7   info.match_type                     7470 non-null   object
 8   info.outcome.by.runs                3563 non-null   float64
 9   info.outcome.winner                 7082 non-null   object
 10  info.player_of_match                6967 non-null   object
 11  info.teams                          7470 non-null   object
 12  info.toss.decision                  7470 non-null   object
 13  info.toss.winner                    7470 non-null   object
 14  info.umpires                        7448 non-null   object
 15  info.venue                          7470 non-null   object
 16  id                                  7470 non-null   int64
 17  info.outcome.by.innings             125 non-null    float64
 18  info.outcome.by.wickets             3517 non-null   float64
 19  info.overs                          6819 non-null   float64
 20  info.outcome.result                 388 non-null    object
 21  info.outcome.method                 372 non-null    object
 22  info.competition                    2650 non-null   object
 23  info.neutral_venue                  1069 non-null   float64
 24  info.outcome.eliminator             46 non-null     object
 25  info.match_type_number              1437 non-null   float64
 26  info.supersubs.Melbourne Renegades  1 non-null      object
 27  info.supersubs.Adelaide Strikers    2 non-null      object
 28  info.supersubs.Hobart Hurricanes    1 non-null      object
 29  info.supersubs.Melbourne Stars      1 non-null      object
 30  info.supersubs.Australia            10 non-null     object
 31  info.supersubs.England              4 non-null      object
 32  info.supersubs.Africa XI            2 non-null      object
 33  info.supersubs.Asia XI              2 non-null      object
 34  info.supersubs.Zimbabwe             3 non-null      object
 35  info.supersubs.Sri Lanka            19 non-null     object
 36  info.supersubs.Bangladesh           4 non-null      object
 37  info.supersubs.New Zealand          15 non-null     object
 38  info.supersubs.India                12 non-null     object
 39  info.supersubs.ICC World XI         2 non-null      object
 40  info.supersubs.South Africa         13 non-null     object
 41  info.supersubs.Pakistan             6 non-null      object
 42  info.bowl_out                       2 non-null      object
 43  info.outcome.bowl_out               2 non-null      object
 44  info.supersubs.West Indies          5 non-null      object
dtypes: float64(7), int64(2), object(36)
memory usage: 2.6+ MB

In [8]:
df['info.match_type'].value_counts()

info.match_type
T20     4082
ODI     2033
Test     628
ODM      372
IT20     332
MDM       23
Name: count, dtype: int64

In [9]:
df = df[df['info.match_type']=='ODI']

In [10]:
df['info.gender'].value_counts()

info.gender
male      1799
female     234
Name: count, dtype: int64

In [11]:
df = df[df['info.gender']=='male']

In [12]:
df.drop(columns=['info.match_type','info.gender'],inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1799 entries, 6 to 7469
Data columns (total 43 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   innings                             1799 non-null   object
 1   meta.data_version                   1799 non-null   float64
 2   meta.created                        1799 non-null   object
 3   meta.revision                       1799 non-null   int64
 4   info.city                           1488 non-null   object
 5   info.dates                          1799 non-null   object
 6   info.outcome.by.runs                842 non-null    float64
 7   info.outcome.winner                 1708 non-null   object
 8   info.player_of_match                1681 non-null   object
 9   info.teams                          1799 non-null   object
 10  info.toss.decision                  1799 non-null   object
 11  info.toss.winner                    1799 non-null   object
 12  info.umpires                        1799 non-null   object
 13  info.venue                          1799 non-null   object
 14  id                                  1799 non-null   int64
 15  info.outcome.by.innings             0 non-null      float64
 16  info.outcome.by.wickets             866 non-null    float64
 17  info.overs                          1799 non-null   float64
 18  info.outcome.result                 91 non-null     object
 19  info.outcome.method                 168 non-null    object
 20  info.competition                    0 non-null      object
 21  info.neutral_venue                  315 non-null    float64
 22  info.outcome.eliminator             2 non-null      object
 23  info.match_type_number              424 non-null    float64
 24  info.supersubs.Melbourne Renegades  0 non-null      object
 25  info.supersubs.Adelaide Strikers    0 non-null      object
 26  info.supersubs.Hobart Hurricanes    0 non-null      object
 27  info.supersubs.Melbourne Stars      0 non-null      object
 28  info.supersubs.Australia            10 non-null     object
 29  info.supersubs.England              4 non-null      object
 30  info.supersubs.Africa XI            2 non-null      object
 31  info.supersubs.Asia XI              2 non-null      object
 32  info.supersubs.Zimbabwe             3 non-null      object
 33  info.supersubs.Sri Lanka            19 non-null     object
 34  info.supersubs.Bangladesh           4 non-null      object
 35  info.supersubs.New Zealand          14 non-null     object
 36  info.supersubs.India                12 non-null     object
 37  info.supersubs.ICC World XI         2 non-null      object
 38  info.supersubs.South Africa         12 non-null     object
 39  info.supersubs.Pakistan             6 non-null      object
 40  info.bowl_out                       0 non-null      object
 41  info.outcome.bowl_out               0 non-null      object
 42  info.supersubs.West Indies          5 non-null      object
dtypes: float64(7), int64(2), object(34)
memory usage: 618.4+ KB

In [14]:
len(df.iloc[0]['innings'])

2

In [15]:
df.head()

,innings,meta.data_version,meta.created,meta.revision,info.city,info.dates,info.outcome.by.runs,info.outcome.winner,info.player_of_match,info.teams,...,info.supersubs.Sri Lanka,info.supersubs.Bangladesh,info.supersubs.New Zealand,info.supersubs.India,info.supersubs.ICC World XI,info.supersubs.South Africa,info.supersubs.Pakistan,info.bowl_out,info.outcome.bowl_out,info.supersubs.West Indies
6,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-01-14,2,Brisbane,[2017-01-13],92.0,Australia,[MS Wade],"[Australia, Pakistan]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-01-18,1,NaN,[2017-01-15],NaN,Pakistan,[Mohammad Hafeez],"[Australia, Pakistan]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.9,2017-01-21,1,Perth,[2017-01-19],NaN,Australia,[SPD Smith],"[Australia, Pakistan]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-01-22,1,NaN,[2017-01-22],86.0,Australia,[DA Warner],"[Australia, Pakistan]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-01-28,1,NaN,[2017-01-26],57.0,Australia,[DA Warner],"[Australia, Pakistan]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df['info.supersubs.India'].value_counts()

info.supersubs.India
SK Raina             4
G Gambhir            2
Y Venugopal Rao      1
Harbhajan Singh      1
M Kartik             1
Jai Prakash Yadav    1
RR Powar             1
Z Khan               1
Name: count, dtype: int64

In [17]:
df['meta.revision'].value_counts()

meta.revision
1    1206
2     509
3      82
4       2
Name: count, dtype: int64

In [18]:
df = df.drop(columns=['meta.revision','meta.data_version','info.outcome.bowl_out','info.bowl_out','info.supersubs.West Indies','info.supersubs.Pakistan','info.supersubs.South Africa','info.supersubs.ICC World XI','info.supersubs.India','info.supersubs.New Zealand','info.supersubs.Bangladesh','info.supersubs.Sri Lanka','info.supersubs.Zimbabwe','info.supersubs.Asia XI','info.supersubs.Africa XI','info.supersubs.England','info.supersubs.Australia','info.supersubs.Melbourne Stars','info.supersubs.Hobart Hurricanes','info.supersubs.Adelaide Strikers','info.supersubs.Melbourne Renegades','info.competition','info.outcome.by.innings'])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1799 entries, 6 to 7469
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   innings                  1799 non-null   object
 1   meta.created             1799 non-null   object
 2   info.city                1488 non-null   object
 3   info.dates               1799 non-null   object
 4   info.outcome.by.runs     842 non-null    float64
 5   info.outcome.winner      1708 non-null   object
 6   info.player_of_match     1681 non-null   object
 7   info.teams               1799 non-null   object
 8   info.toss.decision       1799 non-null   object
 9   info.toss.winner         1799 non-null   object
 10  info.umpires             1799 non-null   object
 11  info.venue               1799 non-null   object
 12  id                       1799 non-null   int64
 13  info.outcome.by.wickets  866 non-null    float64
 14  info.overs               1799 non-null   float64
 15  info.outcome.result      91 non-null     object
 16  info.outcome.method      168 non-null    object
 17  info.neutral_venue       315 non-null    float64
 18  info.outcome.eliminator  2 non-null      object
 19  info.match_type_number   424 non-null    float64
dtypes: float64(5), int64(1), object(14)
memory usage: 295.1+ KB

In [20]:
df.head()

,innings,meta.created,info.city,info.dates,info.outcome.by.runs,info.outcome.winner,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,id,info.outcome.by.wickets,info.overs,info.outcome.result,info.outcome.method,info.neutral_venue,info.outcome.eliminator,info.match_type_number
6,"[{'1st innings': {'team': 'Australia', 'delive...",2017-01-14,Brisbane,[2017-01-13],92.0,Australia,[MS Wade],"[Australia, Pakistan]",bat,Australia,"[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",7,NaN,50.0,NaN,NaN,NaN,NaN,NaN
7,"[{'1st innings': {'team': 'Australia', 'delive...",2017-01-18,NaN,[2017-01-15],NaN,Pakistan,[Mohammad Hafeez],"[Australia, Pakistan]",bat,Australia,"[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,8,6.0,50.0,NaN,NaN,NaN,NaN,NaN
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",2017-01-21,Perth,[2017-01-19],NaN,Australia,[SPD Smith],"[Australia, Pakistan]",field,Australia,"[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,9,7.0,50.0,NaN,NaN,NaN,NaN,NaN
9,"[{'1st innings': {'team': 'Australia', 'delive...",2017-01-22,NaN,[2017-01-22],86.0,Australia,[DA Warner],"[Australia, Pakistan]",bat,Australia,"[CB Gaffaney, MD Martell]",Sydney Cricket Ground,10,NaN,50.0,NaN,NaN,NaN,NaN,NaN
10,"[{'1st innings': {'team': 'Australia', 'delive...",2017-01-28,NaN,[2017-01-26],57.0,Australia,[DA Warner],"[Australia, Pakistan]",bat,Australia,"[SD Fry, C Shamshuddin]",Adelaide Oval,11,NaN,50.0,NaN,NaN,NaN,NaN,NaN

In [21]:
df = df.drop(columns=['info.match_type_number','info.outcome.eliminator','info.neutral_venue','info.outcome.method'])

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1799 entries, 6 to 7469
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   innings                  1799 non-null   object
 1   meta.created             1799 non-null   object
 2   info.city                1488 non-null   object
 3   info.dates               1799 non-null   object
 4   info.outcome.by.runs     842 non-null    float64
 5   info.outcome.winner      1708 non-null   object
 6   info.player_of_match     1681 non-null   object
 7   info.teams               1799 non-null   object
 8   info.toss.decision       1799 non-null   object
 9   info.toss.winner         1799 non-null   object
 10  info.umpires             1799 non-null   object
 11  info.venue               1799 non-null   object
 12  id                       1799 non-null   int64
 13  info.outcome.by.wickets  866 non-null    float64
 14  info.overs               1799 non-null   float64
 15  info.outcome.result      91 non-null     object
dtypes: float64(3), int64(1), object(12)
memory usage: 238.9+ KB

In [23]:
df.head()

,innings,meta.created,info.city,info.dates,info.outcome.by.runs,info.outcome.winner,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,id,info.outcome.by.wickets,info.overs,info.outcome.result
6,"[{'1st innings': {'team': 'Australia', 'delive...",2017-01-14,Brisbane,[2017-01-13],92.0,Australia,[MS Wade],"[Australia, Pakistan]",bat,Australia,"[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",7,NaN,50.0,NaN
7,"[{'1st innings': {'team': 'Australia', 'delive...",2017-01-18,NaN,[2017-01-15],NaN,Pakistan,[Mohammad Hafeez],"[Australia, Pakistan]",bat,Australia,"[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,8,6.0,50.0,NaN
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",2017-01-21,Perth,[2017-01-19],NaN,Australia,[SPD Smith],"[Australia, Pakistan]",field,Australia,"[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,9,7.0,50.0,NaN
9,"[{'1st innings': {'team': 'Australia', 'delive...",2017-01-22,NaN,[2017-01-22],86.0,Australia,[DA Warner],"[Australia, Pakistan]",bat,Australia,"[CB Gaffaney, MD Martell]",Sydney Cricket Ground,10,NaN,50.0,NaN
10,"[{'1st innings': {'team': 'Australia', 'delive...",2017-01-28,NaN,[2017-01-26],57.0,Australia,[DA Warner],"[Australia, Pakistan]",bat,Australia,"[SD Fry, C Shamshuddin]",Adelaide Oval,11,NaN,50.0,NaN

In [24]:
df['info.outcome.result'].value_counts()

info.outcome.result
no result    72
tie          19
Name: count, dtype: int64

In [25]:
pickle.dump(df,open('level_1.pkl','wb'))

In [26]:
df = df[df['info.outcome.result']!='no result']

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1727 entries, 6 to 7469
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   innings                  1727 non-null   object
 1   meta.created             1727 non-null   object
 2   info.city                1426 non-null   object
 3   info.dates               1727 non-null   object
 4   info.outcome.by.runs     842 non-null    float64
 5   info.outcome.winner      1708 non-null   object
 6   info.player_of_match     1679 non-null   object
 7   info.teams               1727 non-null   object
 8   info.toss.decision       1727 non-null   object
 9   info.toss.winner         1727 non-null   object
 10  info.umpires             1727 non-null   object
 11  info.venue               1727 non-null   object
 12  id                       1727 non-null   int64
 13  info.outcome.by.wickets  866 non-null    float64
 14  info.overs               1727 non-null   float64
 15  info.outcome.result      19 non-null     object
dtypes: float64(3), int64(1), object(12)
memory usage: 229.4+ KB

In [28]:
df.tail()

,innings,meta.created,info.city,info.dates,info.outcome.by.runs,info.outcome.winner,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,id,info.outcome.by.wickets,info.overs,info.outcome.result
7464,"[{'1st innings': {'team': 'Afghanistan', 'deli...",2016-07-13,Belfast,[2016-07-12],39.0,Afghanistan,NaN,"[Ireland, Afghanistan]",field,Ireland,"[AJ Neill, IN Ramage]","Civil Service Cricket Club, Stormont",7465,NaN,50.0,NaN
7465,"[{'1st innings': {'team': 'Afghanistan', 'deli...",2016-07-20,Belfast,[2016-07-17],79.0,Afghanistan,NaN,"[Ireland, Afghanistan]",bat,Afghanistan,"[AJ Neill, C Shamshuddin]","Civil Service Cricket Club, Stormont",7466,NaN,50.0,NaN
7466,"[{'1st innings': {'team': 'Ireland', 'deliveri...",2016-07-20,Belfast,[2016-07-19],12.0,Ireland,NaN,"[Ireland, Afghanistan]",field,Afghanistan,"[R Black, C Shamshuddin]","Civil Service Cricket Club, Stormont",7467,NaN,50.0,NaN
7468,"[{'1st innings': {'team': 'Scotland', 'deliver...",2016-08-20,Edinburgh,[2016-08-14],98.0,Scotland,NaN,"[Scotland, United Arab Emirates]",field,United Arab Emirates,"[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7469,NaN,50.0,NaN
7469,[{'1st innings': {'team': 'United Arab Emirate...,2016-08-20,Edinburgh,[2016-08-16],NaN,Scotland,NaN,"[Scotland, United Arab Emirates]",bat,United Arab Emirates,"[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7470,7.0,50.0,NaN

In [29]:
list_of_umpires = df['info.umpires'].to_list()

In [30]:
final_list_of_umpires = []
for i in list_of_umpires:
    if i[0] not in final_list_of_umpires:
        final_list_of_umpires.append(i[0])
    if i[1] not in final_list_of_umpires:
        final_list_of_umpires.append(i[1])

In [31]:
len(final_list_of_umpires)

144

In [32]:
df = df.drop(columns=['meta.created','info.outcome.by.runs','info.player_of_match','info.toss.decision','info.toss.winner','info.outcome.by.wickets','info.overs','info.outcome.result'])

In [33]:
df.head()

,innings,info.city,info.dates,info.outcome.winner,info.teams,info.umpires,info.venue,id
6,"[{'1st innings': {'team': 'Australia', 'delive...",Brisbane,[2017-01-13],Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",7
7,"[{'1st innings': {'team': 'Australia', 'delive...",NaN,[2017-01-15],Pakistan,"[Australia, Pakistan]","[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,8
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Perth,[2017-01-19],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,9
9,"[{'1st innings': {'team': 'Australia', 'delive...",NaN,[2017-01-22],Australia,"[Australia, Pakistan]","[CB Gaffaney, MD Martell]",Sydney Cricket Ground,10
10,"[{'1st innings': {'team': 'Australia', 'delive...",NaN,[2017-01-26],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Adelaide Oval,11

In [34]:
pickle.dump(df,open('level_2.pkl','wb'))

In [35]:
np.size(df['info.venue'].unique())

178

In [36]:
np.size(df['info.city'].unique())

127

In [37]:
df['info.venue'].unique()

array(['Brisbane Cricket Ground, Woolloongabba',
       'Melbourne Cricket Ground',
       'Western Australia Cricket Association Ground',
       'Sydney Cricket Ground', 'Adelaide Oval', 'Manuka Oval',
       'Grange Cricket Club Ground, Raeburn Place', 'Harare Sports Club',
       'Hagley Oval', 'Saxton Oval', 'Eden Park', 'Seddon Park',
       'Westpac Stadium', 'Kennington Oval', 'Edgbaston',
       'Sophia Gardens', 'Mission Road Ground, Mong Kok',
       'Sir Vivian Richards Stadium, North Sound',
       'Kensington Oval, Bridgetown', 'County Ground', "Lord's",
       'Shere Bangla National Stadium', 'Zahur Ahmed Chowdhury Stadium',
       'Himachal Pradesh Cricket Association Stadium', 'Feroz Shah Kotla',
       'Punjab Cricket Association Stadium, Mohali',
       'JSCA International Stadium Complex',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Headingley', 'The Rose Bowl', 'Old Trafford', 'Malahide',
       'Clontarf Cricket Club Ground',
       'Maharashtra Cricket Association Stadium', 'Barabati Stadium',
       'Eden Gardens', 'Greater Noida Sports Complex Ground',
       'Sharjah Cricket Stadium', 'Sheikh Zayed Stadium',
       'Queens Sports Club', 'Perth Stadium', 'Diamond Oval',
       'Boland Park', 'Buffalo Park', 'Providence Stadium',
       'Dubai International Cricket Stadium',
       'ICC Global Cricket Academy',
       'Rangiri Dambulla International Stadium',
       'Sinhalese Sports Club Ground',
       'Darren Sammy National Cricket Stadium, Gros Islet',
       "Queen's Park Oval, Port of Spain", 'Sabina Park, Kingston',
       'Galle International Stadium',
       'Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa',
       'Pallekele International Cricket Stadium',
       'R.Premadasa Stadium, Khettarama', 'Bay Oval', 'University Oval',
       'Cobham Oval (New)', 'Basin Reserve',
       'MA Chidambaram Stadium, Chepauk', 'Holkar Cricket Stadium',
       'M.Chinnaswamy Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha', 'Trent Bridge',
       'Riverside Ground', 'Wankhede Stadium', 'Green Park', 'Kingsmead',
       'SuperSport Park', 'Newlands', 'The Wanderers Stadium',
       "St George's Park",
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'ICC Academy', 'Shere Bangla National Stadium, Mirpur',
       'Bulawayo Athletic Club', 'Old Hararians', 'Mangaung Oval',
       'The Cooper Associates County Ground', 'Bellerive Oval',
       'Warner Park, Basseterre', 'Civil Service Cricket Club, Stormont',
       'Sylhet International Cricket Stadium', 'McLean Park',
       'Kinrara Academy Oval', 'Barsapara Cricket Stadium',
       'Brabourne Stadium', 'Greenfield International Stadium',
       'Kensington Oval, Barbados', 'National Cricket Stadium, Grenada',
       'Darren Sammy National Cricket Stadium, St Lucia',
       'The Village, Malahide',
       'Rajiv Gandhi International Cricket Stadium, Dehradun',
       'Rajiv Gandhi International Stadium, Uppal',
       'Arun Jaitley Stadium', 'Castle Avenue',
       'Bready Cricket Club, Magheramason',
       'Grange Cricket Club, Raeburn Place', 'Affies Park',
       'Wanderers Cricket Ground', 'Senwes Park',
       'Saurashtra Cricket Association Stadium',
       'Sportpark Het Schootsveld', "Queen's Park Oval, Trinidad",
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
       'Mannofield Park', 'National Stadium',
       'Central Broward Regional Park Stadium Turf Ground',
       'Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1)',
       'Tribhuvan University International Cricket Ground',
       'Rawalpindi Cricket Stadium', 'Arnos Vale Ground, Kingstown',
       'Daren Sammy National Cricket Stadium, Gros Islet',
       'St Lawrence Ground', 'Docklands Stadium', 'Vidarbha C.A. Ground',
       'Nehru Stadium', 'Sardar Patel (Gujarat) Stadium, Motera',
       'Madhavrao Scindia Cricket Ground', 'Reliance Stadium',
       'Gaddafi Stadium', 'John Davies Oval', 'Jade Stadium',
       'Arbab Niaz Stadium', 'Multan Cricket Stadium',
       'Shaheed Chandu Stadium', 'Chittagong Divisional Stadium',
       'Narayanganj Osmani Stadium', 'Queenstown Events Centre',
       'Nahar Singh Stadium', 'Nehru Stadium, Fatorda', 'Keenan Stadium',
       'Maharani Usharaje Trust Cricket Ground', 'New Wanderers Stadium',
       'R Premadasa Stadium', "Antigua Recreation Ground, St John's",
       'Beausejour Stadium, Gros Islet',
       "National Cricket Stadium, St George's", 'Gymkhana Club Ground',
       'Sardar Patel Stadium, Motera', 'Sawai Mansingh Stadium',
       'Goodyear Park', 'Sedgars Park', 'Iqbal Stadium',
       'Willowmoore Park', 'Ruaraka Sports Club Ground',
       'Jaffery Sports Club Ground',
       'Indian Petrochemicals Corporation Limited Sports Complex Ground',
       'Andhra Cricket Association-Visakhapatnam District Cricket Association Stadium',
       'Titwood', 'M Chinnaswamy Stadium', 'P Saravanamuttu Stadium',
       'Sector 16 Stadium', 'Vidarbha Cricket Association Ground',
       'Captain Roop Singh Stadium', 'AMI Stadium',
       'Maple Leaf North-West Ground', 'Niaz Stadium, Hyderabad',
       'Sheikhupura Stadium', 'Marrara Cricket Ground', 'OUTsurance Oval',
       'Dubai Sports City Cricket Stadium', 'Windsor Park, Roseau',
       'Zohur Ahmed Chowdhury Stadium', 'VRA Ground',
       'Cambusdoon New Ground', 'Toronto Cricket', 'Chevrolet Park',
       'De Beers Diamond Oval', 'Mombasa Sports Club Ground',
       'Sharjah Cricket Association Stadium', 'Sheikh Abu Naser Stadium',
       'Bangabandhu National Stadium', 'MA Aziz Stadium',
       'W.A.C.A. Ground', 'Khan Shaheb Osman Ali Stadium',
       'Bert Sutcliffe Oval'], dtype=object)

In [38]:
df['info.city'] = np.where(df['info.city'].isnull(),df['info.venue'].str.split().apply(lambda x:x[0]),df['info.city'])

In [39]:
df.head()

,innings,info.city,info.dates,info.outcome.winner,info.teams,info.umpires,info.venue,id
6,"[{'1st innings': {'team': 'Australia', 'delive...",Brisbane,[2017-01-13],Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",7
7,"[{'1st innings': {'team': 'Australia', 'delive...",Melbourne,[2017-01-15],Pakistan,"[Australia, Pakistan]","[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,8
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Perth,[2017-01-19],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,9
9,"[{'1st innings': {'team': 'Australia', 'delive...",Sydney,[2017-01-22],Australia,"[Australia, Pakistan]","[CB Gaffaney, MD Martell]",Sydney Cricket Ground,10
10,"[{'1st innings': {'team': 'Australia', 'delive...",Adelaide,[2017-01-26],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Adelaide Oval,11

In [40]:
df['info.city'].isnull().sum()

0

In [41]:
temp1 = df['info.city'].value_counts().reset_index()

In [42]:
temp1[temp1['count']>=5]

        info.city  count
0          Mirpur     87
1          Harare     78
2          London     61
3         Colombo     59
4           Dubai     50
..            ...    ...
81          Paarl      5
82    East London      5
83         Multan      5
84         Indore      5
85  Greater Noida      5

[86 rows x 2 columns]

In [43]:
temp2 = df['info.venue'].value_counts().reset_index()

In [44]:
temp2[temp2['count']>=5]

                             info.venue  count
0         Shere Bangla National Stadium     87
1                    Harare Sports Club     73
2                   R Premadasa Stadium     44
3                    Queens Sports Club     41
4                  Sheikh Zayed Stadium     40
..                                  ...    ...
85                          Boland Park      5
86  Greater Noida Sports Complex Ground      5
87                        Old Hararians      5
88               Multan Cricket Stadium      5
89                          Senwes Park      5

[90 rows x 2 columns]

In [45]:
cities = temp1[temp1['count']>=5]['info.city'].to_list()

In [46]:
df

,innings,info.city,info.dates,info.outcome.winner,info.teams,info.umpires,info.venue,id
6,"[{'1st innings': {'team': 'Australia', 'delive...",Brisbane,[2017-01-13],Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",7
7,"[{'1st innings': {'team': 'Australia', 'delive...",Melbourne,[2017-01-15],Pakistan,"[Australia, Pakistan]","[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,8
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Perth,[2017-01-19],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,9
9,"[{'1st innings': {'team': 'Australia', 'delive...",Sydney,[2017-01-22],Australia,"[Australia, Pakistan]","[CB Gaffaney, MD Martell]",Sydney Cricket Ground,10
10,"[{'1st innings': {'team': 'Australia', 'delive...",Adelaide,[2017-01-26],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Adelaide Oval,11
...,...,...,...,...,...,...,...,...
7464,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-12],Afghanistan,"[Ireland, Afghanistan]","[AJ Neill, IN Ramage]","Civil Service Cricket Club, Stormont",7465
7465,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-17],Afghanistan,"[Ireland, Afghanistan]","[AJ Neill, C Shamshuddin]","Civil Service Cricket Club, Stormont",7466
7466,"[{'1st innings': {'team': 'Ireland', 'deliveri...",Belfast,[2016-07-19],Ireland,"[Ireland, Afghanistan]","[R Black, C Shamshuddin]","Civil Service Cricket Club, Stormont",7467
7468,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2016-08-14],Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7469
7469,[{'1st innings': {'team': 'United Arab Emirate...,Edinburgh,[2016-08-16],Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7470

In [47]:
df = df[df['info.city'].isin(cities)]

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1618 entries, 6 to 7469
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   innings              1618 non-null   object
 1   info.city            1618 non-null   object
 2   info.dates           1618 non-null   object
 3   info.outcome.winner  1599 non-null   object
 4   info.teams           1618 non-null   object
 5   info.umpires         1618 non-null   object
 6   info.venue           1618 non-null   object
 7   id                   1618 non-null   int64
dtypes: int64(1), object(7)
memory usage: 113.8+ KB

In [49]:
df['info.outcome.winner'] = df['info.outcome.winner'].fillna('Tie')

C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\3351223685.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['info.outcome.winner'] = df['info.outcome.winner'].fillna('Tie')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1618 entries, 6 to 7469
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   innings              1618 non-null   object
 1   info.city            1618 non-null   object
 2   info.dates           1618 non-null   object
 3   info.outcome.winner  1618 non-null   object
 4   info.teams           1618 non-null   object
 5   info.umpires         1618 non-null   object
 6   info.venue           1618 non-null   object
 7   id                   1618 non-null   int64
dtypes: int64(1), object(7)
memory usage: 113.8+ KB

In [51]:
df.iloc[0]['innings']

[{'1st innings': {'team': 'Australia',
   'deliveries': [{0.1: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.2: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.3: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.4: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.5: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'extras': {'wides': 1},
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {0.6: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.7: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.1: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'DA Warner',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.2: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'DA Warner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {1.3: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.4: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.5: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.6: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.1: {'batsman': 'TM Head',
      'bowler': 'Mohammad Amir',
      'non_striker': 'DA Warner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {2.2: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.3: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {2.4: {'batsman': 'TM Head',
      'bowler': 'Mohammad Amir',
      'non_striker': 'DA Warner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {2.5: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.6: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {3.1: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'DA Warner',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {3.2: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'DA Warner',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {3.3: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'DA Warner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {3.4: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'TM Head',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {3.5: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {3.6: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'DA Warner',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {4.1: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {4.2: {'batsman': 'TM Head',
      'bowler': 'Mohammad Amir',
      'non_striker': 'DA Warner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {4.3: {'batsman': 'DA Warner',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'kind': 'bowled', 'player_out': 'DA Warner'}}},
    {4.4: {'batsman': 'SPD Smith',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Mohammad Rizwan'],
       'kind': 'caught',
       'player_out': 'SPD Smith'}}},
    {4.5: {'batsman': 'CA Lynn',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {4.6: {'batsman': 'CA Lynn',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {5.1: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {5.2: {'batsman': 'CA Lynn',
      'bowler': 'Hasan Ali',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {5.3: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {5.4: {'batsman': 'CA Lynn',
      'bowler': 'Hasan Ali',
      'non_striker': 'TM Head',
      'runs': {'batsman': 4, 'extras': 0, 'non_boundary': 1, 'total': 4}}},
    {5.5: {'batsman': 'CA Lynn',
      'bowler': 'Hasan Ali',
      'extras': {'wides': 1},
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {5.6: {'batsman': 'CA Lynn',
      'bowler': 'Hasan Ali',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {5.7: {'batsman': 'CA Lynn',
      'bowler': 'Hasan Ali',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {6.1: {'batsman': 'TM Head',
      'bowler': 'Mohammad Amir',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {6.2: {'batsman': 'TM Head',
      'bowler': 'Mohammad Amir',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {6.3: {'batsman': 'TM Head',
      'bowler': 'Mohammad Amir',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {6.4: {'batsman': 'CA Lynn',
      'bowler': 'Mohammad Amir',
      'non_striker': 'TM Head',
      'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
    {6.5: {'batsman': 'TM Head',
      'bowler': 'Mohammad Amir',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {6.6: {'batsman': 'TM Head',
      'bowler': 'Mohammad Amir',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {7.1: {'batsman': 'CA Lynn',
      'bowler': 'Hasan Ali',
      'non_striker': 'TM Head',
      'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
    {7.2: {'batsman': 'CA Lynn',
      'bowler': 'Hasan Ali',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {7.3: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {7.4: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {7.5: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 4, 'extras': 0, 'non_boundary': 1, 'total': 4}}},
    {7.6: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {8.1: {'batsman': 'CA Lynn',
      'bowler': 'Wahab Riaz',
      'extras': {'wides': 1},
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {8.2: {'batsman': 'CA Lynn',
      'bowler': 'Wahab Riaz',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {8.3: {'batsman': 'TM Head',
      'bowler': 'Wahab Riaz',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {8.4: {'batsman': 'TM Head',
      'bowler': 'Wahab Riaz',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {8.5: {'batsman': 'TM Head',
      'bowler': 'Wahab Riaz',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {8.6: {'batsman': 'TM Head',
      'bowler': 'Wahab Riaz',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {8.7: {'batsman': 'TM Head',
      'bowler': 'Wahab Riaz',
      'non_striker': 'CA Lynn',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {9.1: {'batsman': 'CA Lynn',
      'bowler': 'Hasan Ali',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {9.2: {'batsman': 'CA Lynn',
      'bowler': 'Hasan Ali',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Mohammad Rizwan'],
       'kind': 'caught',
       'player_out': 'CA Lynn'}}},
    {9.3: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {9.4: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {9.5: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {9.6: {'batsman': 'TM Head',
      'bowler': 'Hasan Ali',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {10.1: {'batsman': 'TM Head',
      'bowler': 'Imad Wasim',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {10.2: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {10.3: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {10.4: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {10.5: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {10.6: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {11.1: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {11.2: {'batsman': 'MR Marsh',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {11.3: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {11.4: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {11.5: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {11.6: {'batsman': 'TM Head',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.1: {'batsman': 'TM Head',
      'bowler': 'Imad Wasim',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {12.2: {'batsman': 'TM Head',
      'bowler': 'Imad Wasim',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {12.3: {'batsman': 'TM Head',
      'bowler': 'Imad Wasim',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.4: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {12.5: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.6: {'batsman': 'TM Head',
      'bowler': 'Imad Wasim',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Mohammad Rizwan'],
       'kind': 'caught',
       'player_out': 'TM Head'}}},
    {13.1: {'batsman': 'MR Marsh',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {13.2: {'batsman': 'GJ Maxwell',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {13.3: {'batsman': 'GJ Maxwell',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {13.4: {'batsman': 'GJ Maxwell',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {13.5: {'batsman': 'GJ Maxwell',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {13.6: {'batsman': 'GJ Maxwell',
      'bowler': 'Mohammad Hafeez',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {14.1: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {14.2: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {14.3: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {14.4: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {14.5: {'batsman': 'GJ Maxwell',
      'bowler': 'Imad Wasim',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {14.6: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {15.1: {'batsman': 'GJ Maxwell',
      'bowler': 'Wahab Riaz',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {15.2: {'batsman': 'GJ Maxwell',
      'bowler': 'Wahab Riaz',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {15.3: {'batsman': 'GJ Maxwell',
      'bowler': 'Wahab Riaz',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {15.4: {'batsman': 'GJ Maxwell',
      'bowler': 'Wahab Riaz',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {15.5: {'batsman': 'MR Marsh',
      'bowler': 'Wahab Riaz',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {15.6: {'batsman': 'MR Marsh',
      'bowler': 'Wahab Riaz',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {16.1: {'batsman': 'GJ Maxwell',
      'bowler': 'Imad Wasim',
      'non_striker': 'MR Marsh',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.2: {'batsman': 'MR Marsh',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Mohammad Rizwan'],
       'kind': 'caught',
       'player_out': 'MR Marsh'}}},
    {16.3: {'batsman': 'MS Wade',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.4: {'batsman': 'GJ Maxwell',
      'bowler': 'Imad Wasim',
      'non_striker': 'MS Wade',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.5: {'batsman': 'MS Wade',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.6: {'batsman': 'GJ Maxwell',
      'bowler': 'Imad Wasim',
      'non_striker': 'MS Wade',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {17.1: {'batsman': 'MS Wade',
      'bowler': 'Wahab Riaz',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.2: {'batsman': 'GJ Maxwell',
      'bowler': 'Wahab Riaz',
      'non_striker': 'MS Wade',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.3: {'batsman': 'MS Wade',
      'bowler': 'Wahab Riaz',
      'extras': {'wides': 1},
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {17.4: {'batsman': 'MS Wade',
      'bowler': 'Wahab Riaz',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {17.5: {'batsman': 'MS Wade',
      'bowler': 'Wahab Riaz',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.6: {'batsman': 'GJ Maxwell',
      'bowler': 'Wahab Riaz',
      'non_striker': 'MS Wade',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {17.7: {'batsman': 'GJ Maxwell',
      'bowler': 'Wahab Riaz',
      'non_striker': 'MS Wade',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {18.1: {'batsman': 'GJ Maxwell',
      'bowler': 'Imad Wasim',
      'non_striker': 'MS Wade',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {18.2: {'batsman': 'MS Wade',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {18.3: {'batsman': 'MS Wade',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {18.4: {'batsman': 'MS Wade',
      'bowler': 'Imad Wasim',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {18.5: {'batsman': 'GJ Maxwell',
      'bowler': 'Imad Wasim',
      'non_striker': 'MS Wade',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {18.6: {'batsman': 'GJ Maxwell',
      'bowler': 'Imad Wasim',
      'non_striker': 'MS Wade',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {19.1: {'batsman': 'MS Wade',
      'bowler': 'Mohammad Amir',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {19.2: {'batsman': 'MS Wade',
      'bowler': 'Mohammad Amir',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {19.3: {'batsman': 'GJ Maxwell',
      'bowler': 'Mohammad Amir',
      'non_striker': 'MS Wade',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {19.4: {'batsman': 'MS Wade',
      'bowler': 'Mohammad Amir',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {19.5: {'batsman': 'MS Wade',
      'bowler': 'Mohammad Amir',
      'non_striker': 'GJ Maxwell',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {19.6: {'batsman': 'GJ Maxwell',
      'bowler': 'Mohammad Amir',
      'non_striker': 'MS Wade',

In [52]:
# del_df = []

# for index,row in df.iterrows():
    
#     inning_no = []
#     batting_team = []
#     ball_no = []
#     batsman = []
#     bowler = []
#     non_striker = []
#     runs = []
#     extra = []
#     wicket = []
#     city = []
#     winner = []
#     teams = []
#     umpire = []
#     venue = []
#     match_id = []
#     year = []
    
#     over_no = 0
#     ecnt=0
    
    
    
    
#     for i in range (len(row['innings'])):
#         for inning in (row['innings'][i].keys()):
#             for ball in (row['innings'][i][inning]['deliveries']):
#                 for key in ball.keys():


#                     inning_no.append(inning) #inning no
#                     batting_team.append(row['innings'][i][inning]['team']) #batting team
#                     batsman.append(ball[key]['batsman']) #batsman
#                     bowler.append(ball[key]['bowler'])#bowler
#                     non_striker.append(ball[key]['non_striker']) #non striker
#                     runs.append(ball[key]['runs']['total']) #total runs in that ball
#                     city.append(row['info.city']) #in which city this match is played
#                     winner.append(row['info.outcome.winner']) #winner
#                     teams.append(row['info.teams']) #teams
#                     umpire.append(row['info.umpires'])
#                     venue.append(row['info.venue'])
#                     match_id.append(row['id'])
#                     year.append(row['info.dates'])
                    
                    
#                     try:
#                         wicket.append(ball[key]['wicket']['player_out'])
#                     except:
#                         wicket.append('0')
                        
#                     try:
#                         extra.append(list(ball[key]['extras'].keys())[0])

#                     except:
#                         extra.append('0')
        
        
        
#                     #ball balancing
#                     if (key >= over_no and key < over_no+1):
#                         over_no=over_no  
#                     else:
#                         over_no = int(str(key).split('.')[0])
#                         ecnt = 0   
#                     try:
#                         if((list(ball[key]['extras'].keys())[0]=='noballs') or (list(ball[key]['extras'].keys())[0]=='wides')):
#                             ecnt+=1
#                     except:
#                         ecnt=ecnt
#                     key = key - (ecnt*0.1)
                    
#                     ball_no.append(key) #ball no
                    
#     temp_df = pd.DataFrame({
#         'match_id':match_id,
#         'inning_no':inning_no,
#         'batting_team':batting_team,
#         'ball_no':ball_no,
#         'batsman':batsman,
#         'bowler':bowler,
#         'non_striker':non_striker,
#         'runs':runs,
#         'extra':extra,
#         'wicket':wicket,
#         'city':city,
#         'winner':winner,
#         'teams':teams,
#         'umpire':umpire,
#         'venue':venue,
#         'date':year
#     })
        
#     del_df.append(temp_df)

## At the time of analysis don't forget to seperate out fours and sixes from above code

In [53]:
# del_df = pd.concat(del_df,ignore_index=True)

In [54]:
# pickle.dump(del_df,open('after_extraction.pkl','wb'))

In [55]:
# del_df

In [56]:
# del_df['inning_no'].value_counts()

In [57]:
# del_df[del_df['inning_no']=='New Zealand Super Over']

In [58]:
# del_df[del_df['match_id']==1564].tail(20)

In [59]:
# del_df.info()

In [60]:
# del_df = del_df[del_df['inning_no']!='New Zealand Super Over']
# del_df = del_df[del_df['inning_no']!='England Super Over']
# del_df = del_df[del_df['inning_no']!='Pakistan Super Over']
# del_df = del_df[del_df['inning_no']!='Zimbabwe Super Over']

In [61]:
# cheking matches played in each year

## start

In [62]:
df

,innings,info.city,info.dates,info.outcome.winner,info.teams,info.umpires,info.venue,id
6,"[{'1st innings': {'team': 'Australia', 'delive...",Brisbane,[2017-01-13],Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",7
7,"[{'1st innings': {'team': 'Australia', 'delive...",Melbourne,[2017-01-15],Pakistan,"[Australia, Pakistan]","[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,8
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Perth,[2017-01-19],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,9
9,"[{'1st innings': {'team': 'Australia', 'delive...",Sydney,[2017-01-22],Australia,"[Australia, Pakistan]","[CB Gaffaney, MD Martell]",Sydney Cricket Ground,10
10,"[{'1st innings': {'team': 'Australia', 'delive...",Adelaide,[2017-01-26],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Adelaide Oval,11
...,...,...,...,...,...,...,...,...
7464,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-12],Afghanistan,"[Ireland, Afghanistan]","[AJ Neill, IN Ramage]","Civil Service Cricket Club, Stormont",7465
7465,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-17],Afghanistan,"[Ireland, Afghanistan]","[AJ Neill, C Shamshuddin]","Civil Service Cricket Club, Stormont",7466
7466,"[{'1st innings': {'team': 'Ireland', 'deliveri...",Belfast,[2016-07-19],Ireland,"[Ireland, Afghanistan]","[R Black, C Shamshuddin]","Civil Service Cricket Club, Stormont",7467
7468,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2016-08-14],Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7469
7469,[{'1st innings': {'team': 'United Arab Emirate...,Edinburgh,[2016-08-16],Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7470

In [63]:
temp3 = []
for date in df['info.dates']:
    temp3.append(str(date[0]))

In [64]:
temp3[0].split('-')

['2017', '01', '13']

In [65]:
year = []
month = []
day = []
for i in temp3:   
    year.append(i.split('-')[0])
    month.append(i.split('-')[1])    
    day.append(i.split('-')[2])

In [66]:
year

['2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2017',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2017',
 '2017',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2017',
 '2017',
 '2017',
 '2017',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2018',
 '2018',
 '2018',
 '2019',
 '2019',
 '2019',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2019',
 '2019',
 '2019',
 '2019',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2019',
 '2019',
 '2019',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2007',
 '2007',
 '2007',
 '2007',
 '2006',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2008',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 ...]

In [67]:
df['year'] = year    
df['month'] = month
df['day']= day

C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\1381356328.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = year
C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\1381356328.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = month
C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\1381356328.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day']= day

In [68]:
df.groupby('year').count()['info.dates']

year
2004      1
2005     59
2006    104
2007    138
2008     83
2009    108
2010     97
2011    133
2012     78
2013    109
2014    107
2015    137
2016     85
2017    110
2018    117
2019    121
2020     31
Name: info.dates, dtype: int64

In [69]:
temp4 =df[df['year']=='2007']

In [70]:
temp5 = temp4[temp4['month']<='04']

In [71]:
temp5[temp5['month']>='03'].shape

(50, 11)

In [72]:
df

,innings,info.city,info.dates,info.outcome.winner,info.teams,info.umpires,info.venue,id,year,month,day
6,"[{'1st innings': {'team': 'Australia', 'delive...",Brisbane,[2017-01-13],Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",7,2017,01,13
7,"[{'1st innings': {'team': 'Australia', 'delive...",Melbourne,[2017-01-15],Pakistan,"[Australia, Pakistan]","[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,8,2017,01,15
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Perth,[2017-01-19],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,9,2017,01,19
9,"[{'1st innings': {'team': 'Australia', 'delive...",Sydney,[2017-01-22],Australia,"[Australia, Pakistan]","[CB Gaffaney, MD Martell]",Sydney Cricket Ground,10,2017,01,22
10,"[{'1st innings': {'team': 'Australia', 'delive...",Adelaide,[2017-01-26],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Adelaide Oval,11,2017,01,26
...,...,...,...,...,...,...,...,...,...,...,...
7464,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-12],Afghanistan,"[Ireland, Afghanistan]","[AJ Neill, IN Ramage]","Civil Service Cricket Club, Stormont",7465,2016,07,12
7465,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-17],Afghanistan,"[Ireland, Afghanistan]","[AJ Neill, C Shamshuddin]","Civil Service Cricket Club, Stormont",7466,2016,07,17
7466,"[{'1st innings': {'team': 'Ireland', 'deliveri...",Belfast,[2016-07-19],Ireland,"[Ireland, Afghanistan]","[R Black, C Shamshuddin]","Civil Service Cricket Club, Stormont",7467,2016,07,19
7468,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2016-08-14],Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7469,2016,08,14
7469,[{'1st innings': {'team': 'United Arab Emirate...,Edinburgh,[2016-08-16],Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7470,2016,08,16

In [73]:
df['year'] = df['year'].astype('int')
df['month'] = df['month'].astype('int')
df['day'] = df['day'].astype('int')

C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\1808944061.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['year'].astype('int')
C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\1808944061.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = df['month'].astype('int')
C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\1808944061.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day'] = df['day'].astype('int')

In [74]:
temp4 = df[df['year'].isin([2019])]
temp5 = temp4[temp4['month'].isin([5,6,7])]
temp5.shape

(61, 11)

In [75]:
df

,innings,info.city,info.dates,info.outcome.winner,info.teams,info.umpires,info.venue,id,year,month,day
6,"[{'1st innings': {'team': 'Australia', 'delive...",Brisbane,[2017-01-13],Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",7,2017,1,13
7,"[{'1st innings': {'team': 'Australia', 'delive...",Melbourne,[2017-01-15],Pakistan,"[Australia, Pakistan]","[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,8,2017,1,15
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Perth,[2017-01-19],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,9,2017,1,19
9,"[{'1st innings': {'team': 'Australia', 'delive...",Sydney,[2017-01-22],Australia,"[Australia, Pakistan]","[CB Gaffaney, MD Martell]",Sydney Cricket Ground,10,2017,1,22
10,"[{'1st innings': {'team': 'Australia', 'delive...",Adelaide,[2017-01-26],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Adelaide Oval,11,2017,1,26
...,...,...,...,...,...,...,...,...,...,...,...
7464,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-12],Afghanistan,"[Ireland, Afghanistan]","[AJ Neill, IN Ramage]","Civil Service Cricket Club, Stormont",7465,2016,7,12
7465,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-17],Afghanistan,"[Ireland, Afghanistan]","[AJ Neill, C Shamshuddin]","Civil Service Cricket Club, Stormont",7466,2016,7,17
7466,"[{'1st innings': {'team': 'Ireland', 'deliveri...",Belfast,[2016-07-19],Ireland,"[Ireland, Afghanistan]","[R Black, C Shamshuddin]","Civil Service Cricket Club, Stormont",7467,2016,7,19
7468,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2016-08-14],Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7469,2016,8,14
7469,[{'1st innings': {'team': 'United Arab Emirate...,Edinburgh,[2016-08-16],Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",7470,2016,8,16

In [76]:
pickle.dump(df,open('with_series.pkl','wb'))

## above importat dataframe

In [77]:
# df = df[df['year'].isin([2007,2011,2015,2019])]

In [78]:
df['year'] = df['year'].astype('str')
df['month'] = df['month'].astype('str')
df['day'] = df['day'].astype('str')

C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\114698085.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['year'].astype('str')
C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\114698085.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = df['month'].astype('str')
C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\114698085.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day'] = df['day'].astype('str')

In [79]:
def z(df):
    d = int(df['day'])
    if (d>=1 and d<=9):
        dt=df['year']+df['month']+'0'+df['day']
    else:
        dt=df['year']+df['month']+df['day']
       
    return dt

In [80]:
df['temp_date'] = df.apply(z,axis=1)

C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\2613288225.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['temp_date'] = df.apply(z,axis=1)

In [81]:
df['temp_date'] = df['temp_date'].astype('int')

C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\3250300083.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['temp_date'] = df['temp_date'].astype('int')

In [82]:
df2007 = df[df['temp_date'].between(2007313,2007428)]

In [83]:
df2011 = df[df['temp_date'].between(2011219,2011402)]

In [84]:
df2015 = df[df['temp_date'].between(2015214,2015329)]

In [85]:
df2019 = df[df['temp_date'].between(2019530,2019714)]

In [86]:
# df = pd.concat([df2007,df2011,df2015,df2019],axis=0)

## now commom things starts

In [87]:
df.head()

,innings,info.city,info.dates,info.outcome.winner,info.teams,info.umpires,info.venue,id,year,month,day,temp_date
6,"[{'1st innings': {'team': 'Australia', 'delive...",Brisbane,[2017-01-13],Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",7,2017,1,13,2017113
7,"[{'1st innings': {'team': 'Australia', 'delive...",Melbourne,[2017-01-15],Pakistan,"[Australia, Pakistan]","[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,8,2017,1,15,2017115
8,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Perth,[2017-01-19],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,9,2017,1,19,2017119
9,"[{'1st innings': {'team': 'Australia', 'delive...",Sydney,[2017-01-22],Australia,"[Australia, Pakistan]","[CB Gaffaney, MD Martell]",Sydney Cricket Ground,10,2017,1,22,2017122
10,"[{'1st innings': {'team': 'Australia', 'delive...",Adelaide,[2017-01-26],Australia,"[Australia, Pakistan]","[SD Fry, C Shamshuddin]",Adelaide Oval,11,2017,1,26,2017126

In [88]:
df = df[df['temp_date']!=2019616]
df = df[df['temp_date']!=2019604]
df = df[df['temp_date']!=2015224]
df = df[df['temp_date']!=2015324]
df = df[df['temp_date']!=2011314]
df = df[df['temp_date']!=2007403]

In [89]:
del_df = []

for index,row in df.iterrows():
    
    inning_no = []
    batting_team = []
    ball_no = []
    batsman = []
    bowler = []
    non_striker = []
    runs = []
    extra = []
    wicket = []
    city = []
    winner = []
    teams = []
    umpire = []
    venue = []
    match_id = []
    year = []
    
    over_no = 0
    ecnt=0
    
    
    
    
    for i in range (len(row['innings'])):
        for inning in (row['innings'][i].keys()):
            for ball in (row['innings'][i][inning]['deliveries']):
                for key in ball.keys():


                    inning_no.append(inning) #inning no
                    batting_team.append(row['innings'][i][inning]['team']) #batting team
                    batsman.append(ball[key]['batsman']) #batsman
                    bowler.append(ball[key]['bowler'])#bowler
                    non_striker.append(ball[key]['non_striker']) #non striker
                    runs.append(ball[key]['runs']['total']) #total runs in that ball
                    city.append(row['info.city']) #in which city this match is played
                    winner.append(row['info.outcome.winner']) #winner
                    teams.append(row['info.teams']) #teams
                    umpire.append(row['info.umpires'])
                    venue.append(row['info.venue'])
                    match_id.append(row['id'])
                    year.append(row['info.dates'])
                    
                    
                    try:
                        wicket.append(ball[key]['wicket']['player_out'])
                    except:
                        wicket.append('0')
                        
                    try:
                        extra.append(list(ball[key]['extras'].keys())[0])

                    except:
                        extra.append('0')
        
        
        
                    #ball balancing
                    if (key >= over_no and key < over_no+1):
                        over_no=over_no  
                    else:
                        over_no = int(str(key).split('.')[0])
                        ecnt = 0   
                    try:
                        if((list(ball[key]['extras'].keys())[0]=='noballs') or (list(ball[key]['extras'].keys())[0]=='wides')):
                            ecnt+=1
                    except:
                        ecnt=ecnt
                    key = key - (ecnt*0.1)
                    
                    ball_no.append(key) #ball no
                    
    temp_df = pd.DataFrame({
        'match_id':match_id,
        'inning_no':inning_no,
        'batting_team':batting_team,
        'ball_no':ball_no,
        'batsman':batsman,
        'bowler':bowler,
        'non_striker':non_striker,
        'runs':runs,
        'extra':extra,
        'wicket':wicket,
        'city':city,
        'winner':winner,
        'teams':teams,
        'umpire':umpire,
        'venue':venue,
        'date':year
    })
        
    del_df.append(temp_df)

In [90]:
del_df = pd.concat(del_df,ignore_index=True)

In [91]:
pickle.dump(del_df,open('after_extraction_not1618.pkl','wb'))

In [92]:
del_df

,match_id,inning_no,batting_team,ball_no,batsman,bowler,non_striker,runs,extra,wicket,city,winner,teams,umpire,venue,date
0,7,1st innings,Australia,0.1,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
1,7,1st innings,Australia,0.2,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
2,7,1st innings,Australia,0.3,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
3,7,1st innings,Australia,0.4,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
4,7,1st innings,Australia,0.4,DA Warner,Mohammad Amir,TM Head,1,wides,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882274,7470,2nd innings,Scotland,46.6,PL Mommsen,Mohammad Shahzad (2),RD Berrington,0,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]
882275,7470,2nd innings,Scotland,47.1,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]
882276,7470,2nd innings,Scotland,47.2,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]
882277,7470,2nd innings,Scotland,47.3,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]
882278,7470,2nd innings,Scotland,47.4,RD Berrington,Rohan Mustafa,PL Mommsen,4,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]

In [93]:
del_df['inning_no'].value_counts()

inning_no
1st innings               472721
2nd innings               409538
New Zealand Super Over         7
England Super Over             6
Pakistan Super Over            4
Zimbabwe Super Over            3
Name: count, dtype: int64

In [94]:
del_df[del_df['inning_no']=='New Zealand Super Over']

,match_id,inning_no,batting_team,ball_no,batsman,bowler,non_striker,runs,extra,wicket,city,winner,teams,umpire,venue,date
145559,1564,New Zealand Super Over,New Zealand,0.0,JDS Neesham,JC Archer,MJ Guptill,1,wides,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145560,1564,New Zealand Super Over,New Zealand,0.1,JDS Neesham,JC Archer,MJ Guptill,2,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145561,1564,New Zealand Super Over,New Zealand,0.2,JDS Neesham,JC Archer,MJ Guptill,6,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145562,1564,New Zealand Super Over,New Zealand,0.3,JDS Neesham,JC Archer,MJ Guptill,2,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145563,1564,New Zealand Super Over,New Zealand,0.4,JDS Neesham,JC Archer,MJ Guptill,2,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145564,1564,New Zealand Super Over,New Zealand,0.5,JDS Neesham,JC Archer,MJ Guptill,1,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145565,1564,New Zealand Super Over,New Zealand,0.6,MJ Guptill,JC Archer,JDS Neesham,1,0,MJ Guptill,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]

In [95]:
del_df[del_df['match_id']==1564].tail(20)

,match_id,inning_no,batting_team,ball_no,batsman,bowler,non_striker,runs,extra,wicket,city,winner,teams,umpire,venue,date
145546,1564,2nd innings,England,48.6,JC Archer,JDS Neesham,BA Stokes,0,0,JC Archer,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145547,1564,2nd innings,England,49.1,BA Stokes,TA Boult,AU Rashid,0,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145548,1564,2nd innings,England,49.2,BA Stokes,TA Boult,AU Rashid,0,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145549,1564,2nd innings,England,49.3,BA Stokes,TA Boult,AU Rashid,6,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145550,1564,2nd innings,England,49.4,BA Stokes,TA Boult,AU Rashid,6,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145551,1564,2nd innings,England,49.5,BA Stokes,TA Boult,AU Rashid,1,0,AU Rashid,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145552,1564,2nd innings,England,49.6,BA Stokes,TA Boult,MA Wood,1,0,MA Wood,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145553,1564,England Super Over,England,0.1,BA Stokes,TA Boult,JC Buttler,3,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145554,1564,England Super Over,England,0.2,JC Buttler,TA Boult,BA Stokes,1,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145555,1564,England Super Over,England,0.3,BA Stokes,TA Boult,JC Buttler,4,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145556,1564,England Super Over,England,0.4,BA Stokes,TA Boult,JC Buttler,1,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145557,1564,England Super Over,England,0.5,JC Buttler,TA Boult,BA Stokes,2,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145558,1564,England Super Over,England,0.6,JC Buttler,TA Boult,BA Stokes,4,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145559,1564,New Zealand Super Over,New Zealand,0.0,JDS Neesham,JC Archer,MJ Guptill,1,wides,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145560,1564,New Zealand Super Over,New Zealand,0.1,JDS Neesham,JC Archer,MJ Guptill,2,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145561,1564,New Zealand Super Over,New Zealand,0.2,JDS Neesham,JC Archer,MJ Guptill,6,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145562,1564,New Zealand Super Over,New Zealand,0.3,JDS Neesham,JC Archer,MJ Guptill,2,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145563,1564,New Zealand Super Over,New Zealand,0.4,JDS Neesham,JC Archer,MJ Guptill,2,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145564,1564,New Zealand Super Over,New Zealand,0.5,JDS Neesham,JC Archer,MJ Guptill,1,0,0,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]
145565,1564,New Zealand Super Over,New Zealand,0.6,MJ Guptill,JC Archer,JDS Neesham,1,0,MJ Guptill,London,Tie,"[England, New Zealand]","[HDPK Dharmasena, M Erasmus]",Lord's,[2019-07-14]

In [96]:
del_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882279 entries, 0 to 882278
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   match_id      882279 non-null  int64
 1   inning_no     882279 non-null  object
 2   batting_team  882279 non-null  object
 3   ball_no       882279 non-null  float64
 4   batsman       882279 non-null  object
 5   bowler        882279 non-null  object
 6   non_striker   882279 non-null  object
 7   runs          882279 non-null  int64
 8   extra         882279 non-null  object
 9   wicket        882279 non-null  object
 10  city          882279 non-null  object
 11  winner        882279 non-null  object
 12  teams         882279 non-null  object
 13  umpire        882279 non-null  object
 14  venue         882279 non-null  object
 15  date          882279 non-null  object
dtypes: float64(1), int64(2), object(13)
memory usage: 107.7+ MB

In [97]:
del_df = del_df[del_df['inning_no']!='New Zealand Super Over']
del_df = del_df[del_df['inning_no']!='England Super Over']
del_df = del_df[del_df['inning_no']!='Pakistan Super Over']
del_df = del_df[del_df['inning_no']!='Zimbabwe Super Over']

## end only odi world cup not series

In [98]:
del_df['batting_team'].value_counts()

batting_team
India                       96830
Australia                   93721
Sri Lanka                   93304
England                     84760
Pakistan                    82000
South Africa                75538
New Zealand                 68891
West Indies                 66365
Bangladesh                  58204
Zimbabwe                    51760
Ireland                     25499
Afghanistan                 22949
Scotland                    14490
United Arab Emirates        11212
Kenya                        5914
Canada                       5710
Papua New Guinea             4027
Hong Kong                    3800
Netherlands                  3774
United States of America     2884
Bermuda                      2526
Oman                         2308
Nepal                        2023
Asia XI                      1241
Africa XI                    1184
Namibia                       887
ICC World XI                  458
Name: count, dtype: int64

In [99]:
del_df

,match_id,inning_no,batting_team,ball_no,batsman,bowler,non_striker,runs,extra,wicket,city,winner,teams,umpire,venue,date
0,7,1st innings,Australia,0.1,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
1,7,1st innings,Australia,0.2,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
2,7,1st innings,Australia,0.3,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
3,7,1st innings,Australia,0.4,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
4,7,1st innings,Australia,0.4,DA Warner,Mohammad Amir,TM Head,1,wides,0,Brisbane,Australia,"[Australia, Pakistan]","[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",[2017-01-13]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882274,7470,2nd innings,Scotland,46.6,PL Mommsen,Mohammad Shahzad (2),RD Berrington,0,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]
882275,7470,2nd innings,Scotland,47.1,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]
882276,7470,2nd innings,Scotland,47.2,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]
882277,7470,2nd innings,Scotland,47.3,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]
882278,7470,2nd innings,Scotland,47.4,RD Berrington,Rohan Mustafa,PL Mommsen,4,0,0,Edinburgh,Scotland,"[Scotland, United Arab Emirates]","[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",[2016-08-16]

In [100]:
team1 = []
team2 = []
for teams in del_df['teams']:
    team1.append(teams[0])
    team2.append(teams[1])

In [101]:
del_df['team1'] = team1
del_df['team2'] = team2

In [102]:
def bowlling_team(df):
    if(df['batting_team']==df['team1']):
        return df['team2']
    else:
        return df['team1']

In [103]:
del_df['bowlling_team'] = del_df.apply(bowlling_team,axis=1)

In [104]:
del_df.drop(columns=['team1','team2','date','teams','umpire'],inplace=True)

In [105]:
del_df['batting_team'].value_counts()

batting_team
India                       96830
Australia                   93721
Sri Lanka                   93304
England                     84760
Pakistan                    82000
South Africa                75538
New Zealand                 68891
West Indies                 66365
Bangladesh                  58204
Zimbabwe                    51760
Ireland                     25499
Afghanistan                 22949
Scotland                    14490
United Arab Emirates        11212
Kenya                        5914
Canada                       5710
Papua New Guinea             4027
Hong Kong                    3800
Netherlands                  3774
United States of America     2884
Bermuda                      2526
Oman                         2308
Nepal                        2023
Asia XI                      1241
Africa XI                    1184
Namibia                       887
ICC World XI                  458
Name: count, dtype: int64

In [106]:
con_list = ['Canada','Kenya','Bermuda','ICC World XI','Namibia','Africa XI','Asia XI','Nepal','Oman','Bermuda','Papua New Guinea','Hong Kong','United States of America']
def remove_contries(df):
    if df['batting_team'] in con_list:
        return '0'
    elif (df['bowlling_team'] in con_list):
        return '0'
    else:
        return df['batting_team']

In [107]:
del_df['batting_team'] = del_df.apply(remove_contries,axis=1)

In [108]:
del_df = del_df[del_df['batting_team']!='0']

In [109]:
del_df

,match_id,inning_no,batting_team,ball_no,batsman,bowler,non_striker,runs,extra,wicket,city,winner,venue,bowlling_team
0,7,1st innings,Australia,0.1,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Pakistan
1,7,1st innings,Australia,0.2,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Pakistan
2,7,1st innings,Australia,0.3,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Pakistan
3,7,1st innings,Australia,0.4,DA Warner,Mohammad Amir,TM Head,0,0,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Pakistan
4,7,1st innings,Australia,0.4,DA Warner,Mohammad Amir,TM Head,1,wides,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Pakistan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882274,7470,2nd innings,Scotland,46.6,PL Mommsen,Mohammad Shahzad (2),RD Berrington,0,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates
882275,7470,2nd innings,Scotland,47.1,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates
882276,7470,2nd innings,Scotland,47.2,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates
882277,7470,2nd innings,Scotland,47.3,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates
882278,7470,2nd innings,Scotland,47.4,RD Berrington,Rohan Mustafa,PL Mommsen,4,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates

In [110]:
del_df['score'] = del_df.groupby(['match_id','inning_no'])['runs'].cumsum()

C:\Users\Ayush\AppData\Local\Temp\ipykernel_17240\3797452796.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del_df['score'] = del_df.groupby(['match_id','inning_no'])['runs'].cumsum()

In [111]:
pickle.dump(del_df,open('backup_of_both_innings_data','wb'))

In [112]:
target_df = del_df.groupby(['match_id','inning_no'])['runs'].sum().reset_index()

In [113]:
target_df['runs'] = target_df['runs']+1

In [114]:
target_df = target_df[target_df['inning_no']=='1st innings']

In [115]:
target_df = target_df.drop(columns=['inning_no'])

In [116]:
del_df = del_df[del_df['inning_no']=='2nd innings']

In [117]:
target_df = target_df.rename(columns={'runs':'target'})

In [118]:
del_df = del_df.merge(target_df)

In [119]:
del_df

,match_id,inning_no,batting_team,ball_no,batsman,bowler,non_striker,runs,extra,wicket,city,winner,venue,bowlling_team,score,target
0,7,2nd innings,Pakistan,0.1,Azhar Ali,MA Starc,Sharjeel Khan,0,0,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Australia,0,269
1,7,2nd innings,Pakistan,0.2,Azhar Ali,MA Starc,Sharjeel Khan,0,0,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Australia,0,269
2,7,2nd innings,Pakistan,0.3,Azhar Ali,MA Starc,Sharjeel Khan,0,0,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Australia,0,269
3,7,2nd innings,Pakistan,0.4,Azhar Ali,MA Starc,Sharjeel Khan,1,0,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Australia,1,269
4,7,2nd innings,Pakistan,0.5,Sharjeel Khan,MA Starc,Azhar Ali,0,0,0,Brisbane,Australia,"Brisbane Cricket Ground, Woolloongabba",Australia,1,269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386778,7470,2nd innings,Scotland,46.6,PL Mommsen,Mohammad Shahzad (2),RD Berrington,0,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates,225,229
386779,7470,2nd innings,Scotland,47.1,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates,225,229
386780,7470,2nd innings,Scotland,47.2,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates,225,229
386781,7470,2nd innings,Scotland,47.3,RD Berrington,Rohan Mustafa,PL Mommsen,0,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates,225,229
386782,7470,2nd innings,Scotland,47.4,RD Berrington,Rohan Mustafa,PL Mommsen,4,0,0,Edinburgh,Scotland,"Grange Cricket Club Ground, Raeburn Place",United Arab Emirates,229,229

In [120]:
del_df['runs_require'] = del_df['target'] - del_df['score']

In [121]:
del_df['runs_require'] = del_df['runs_require'].apply(lambda x:0 if x<0 else x)

In [122]:
del_df['ball_no'] = del_df['ball_no'].astype('str')

In [123]:
del_df['wicket'] = del_df['wicket'].apply(lambda x:x if x=='0' else '1')

In [124]:
del_df['wicket'] = del_df['wicket'].astype('int')

In [125]:
del_df['wicket_no'] = del_df.groupby('match_id')['wicket'].cumsum()

In [126]:
del_df['wickets_remaining'] = 10 - del_df['wicket_no']

In [127]:
del_df = del_df.drop(columns=['inning_no','runs','extra','wicket','venue','wicket_no'])

In [128]:
del_df['ball_no'] = round(del_df['ball_no'].astype('float'),1)

In [129]:
del_df['ball_no'] = del_df['ball_no'].astype('str')

In [130]:
del_df['over'] = del_df['ball_no'].str.split('.').apply(lambda x:x[0])
del_df['ball'] = del_df['ball_no'].str.split('.').apply(lambda x:x[1])

In [131]:
del_df['over'] = del_df['over'].astype('int')

In [132]:
del_df['ball'] = del_df['ball'].astype('float')

In [133]:
del_df['ball'] = del_df['ball'].round()
del_df['ball'] = del_df['ball'].astype('int')

In [134]:
del_df['balls_thrown'] = (del_df['over']*6 + del_df['ball'])
del_df['balls_remaining'] = 300 - (del_df['over']*6 + del_df['ball'])

In [135]:
del_df = del_df.drop(columns=['ball_no','over','ball','batsman','bowler','non_striker'])

In [136]:
del_df

,match_id,batting_team,city,winner,bowlling_team,score,target,runs_require,wickets_remaining,balls_thrown,balls_remaining
0,7,Pakistan,Brisbane,Australia,Australia,0,269,269,10,1,299
1,7,Pakistan,Brisbane,Australia,Australia,0,269,269,10,2,298
2,7,Pakistan,Brisbane,Australia,Australia,0,269,269,10,3,297
3,7,Pakistan,Brisbane,Australia,Australia,1,269,268,10,4,296
4,7,Pakistan,Brisbane,Australia,Australia,1,269,268,10,5,295
...,...,...,...,...,...,...,...,...,...,...,...
386778,7470,Scotland,Edinburgh,Scotland,United Arab Emirates,225,229,4,7,282,18
386779,7470,Scotland,Edinburgh,Scotland,United Arab Emirates,225,229,4,7,283,17
386780,7470,Scotland,Edinburgh,Scotland,United Arab Emirates,225,229,4,7,284,16
386781,7470,Scotland,Edinburgh,Scotland,United Arab Emirates,225,229,4,7,285,15
386782,7470,Scotland,Edinburgh,Scotland,United Arab Emirates,229,229,0,7,286,14

In [137]:
def result(df):
    if(df['batting_team']==df['winner']):
        return 1
    else:
        return 0

In [138]:
del_df['result'] = del_df.apply(result,axis=1)

In [139]:
del_df = del_df.drop(columns=['winner','match_id'])

In [140]:
del_df['crr'] = (del_df['score']*6 )/ del_df['balls_thrown']
del_df['rrr'] = (del_df['runs_require']*6) / del_df['balls_remaining']

In [141]:
del_df[['target','runs_require','balls_remaining','wickets_remaining','result','crr','rrr']].corr()['result']

target              -0.468165
runs_require        -0.370242
balls_remaining      0.040135
wickets_remaining    0.323270
result               1.000000
crr                  0.178134
rrr                 -0.209430
Name: result, dtype: float64

In [142]:
# when i take all data (not only world cup)
# target              -0.466911
# runs_require        -0.370169
# balls_remaining      0.038290
# wickets_remaining    0.321266
# result               1.000000
# crr                  0.171039
# rrr                 -0.210015

In [143]:
del_df['crr'] = round(del_df['crr'],3)
del_df['rrr'] = round(del_df['rrr'],3)

In [144]:
def resolve_infinity_val_in_crr(df):
    if(df['balls_thrown']==0):
        return df['score']
    else:
        return df['crr']

In [145]:
del_df['crr'] = del_df.apply(resolve_infinity_val_in_crr,axis=1)

In [146]:
final_df = del_df[['batting_team','bowlling_team','city','target','runs_require','balls_remaining','wickets_remaining','crr','rrr','result']]

In [147]:
final_df = final_df[final_df['balls_remaining']!=0]

In [148]:
temp11 = final_df['city'].value_counts().reset_index()
final_df = final_df.merge(temp11)

def adjust_city(df):
    if(df['count']<1300):
        return 'Unknown'
    else:
        return df['city']

final_df['city'] = final_df.apply(adjust_city,axis=1)
final_df.drop(columns=['count'],inplace=True)

In [149]:
final_df.describe()

,target,runs_require,balls_remaining,wickets_remaining,crr,rrr,result
count,386635.000000,386635.000000,386635.000000,386635.000000,386635.000000,386635.000000,386635.000000
mean,260.646501,154.286001,169.924681,7.088962,4.840715,6.210669,0.486844
std,59.668690,81.942257,79.414532,2.355326,1.544949,8.899722,0.499828
min,45.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,223.000000,91.000000,106.000000,6.000000,4.017000,4.202000,0.000000
50%,261.000000,153.000000,175.000000,8.000000,4.780000,5.641000,0.000000
75%,301.000000,214.000000,238.000000,9.000000,5.600000,7.098000,1.000000
max,482.000000,481.000000,300.000000,10.000000,66.000000,1038.000000,1.000000

In [150]:
final_df = final_df.sample(frac=1)

In [151]:
from sklearn.model_selection import train_test_split

In [152]:
train,test = train_test_split(final_df,test_size=0.2,random_state=42)

In [153]:
y_train = train['result']
x_train = train.drop(columns=['result'])

y_test = test['result']
x_test = test.drop(columns=['result'])

In [154]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier

from sklearn.metrics import r2_score,mean_absolute_error,accuracy_score

In [155]:
step1 = ColumnTransformer(transformers=[
    ('col_tr',OneHotEncoder(sparse=False,drop='first'),[0,1,2])
],remainder='passthrough')

step2 = StandardScaler()

step3 = RandomForestClassifier()

In [156]:
pipe = Pipeline(steps=[
    ('step1', step1),
    ('step2',step2),
    ('step3',step3)
])

In [157]:
pipe.fit(x_train,y_train)

C:\Users\Ayush\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('col_tr',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  [0, 1, 2])])),
                ('step2', StandardScaler()),
                ('step3', RandomForestClassifier())])

In [158]:
predictions = pipe.predict(x_test)

In [159]:
print('r2 score : ',r2_score(y_test,predictions))
print('mean absolute error : ',mean_absolute_error(y_test,predictions))
print('accuracy score : ',accuracy_score(y_test,predictions))

r2 score :  0.9991200319163253
mean absolute error :  0.00021984559080269505
accuracy score :  0.9997801544091973

In [160]:
pipe.predict([['New Zealand','India','Mumbai',398,177,96,6,1.083,1.843]])

C:\Users\Ayush\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [161]:
final_df['city'].unique()

array(['Bangalore', 'Benoni', 'Bulawayo', 'Christchurch', 'Colombo',
       'Jamaica', 'Cardiff', 'Adelaide', 'Karachi', 'Hamilton', 'Dunedin',
       'Guyana', 'Dublin', 'Mumbai', 'Pallekele', 'Sydney', 'Dubai',
       'Unknown', 'Mirpur', 'Indore', 'St Kitts', 'Potchefstroom',
       'Nagpur', 'Perth', 'Bloemfontein', 'Nottingham', 'Visakhapatnam',
       'Bristol', 'Brisbane', 'Rawalpindi', 'Johannesburg', 'Barbados',
       'Nelson', 'Chandigarh', 'Chester-le-Street', 'Durban',
       'Wellington', 'Port Elizabeth', 'Auckland', 'Abu Dhabi', 'Sharjah',
       'St Vincent', 'St Lucia', 'Melbourne', 'Hobart', 'Delhi', 'Harare',
       'Rangiri', 'London', 'Antigua', 'Southampton', 'Grenada',
       'Cuttack', 'Manchester', 'Chennai', 'Belfast', 'Napier',
       'Birmingham', 'Hambantota', 'Centurion', 'Cape Town', 'Lahore',
       'Leeds', 'Canberra', 'Ahmedabad', 'Kanpur', 'Chittagong',
       'Fatullah', 'Mount Maunganui', 'Kuala Lumpur', 'Greater Noida',
       'Dhaka', 'Jaipur', 'Rajkot', 'Kolkata', 'Trinidad', 'Hyderabad',
       'Pune', 'Edinburgh'], dtype=object)

In [162]:
#LOGISTIC REGRESSOR
# r2 score :  0.4227668982065783
# mean absolute error :  0.14419284337941468
# accuracy score :  0.8558071566205853

In [163]:
#RANDOMFOREST CLASSIFIER
# r2 score :  0.9993787625810295
# mean absolute error :  0.00015518512291954944
# accuracy score :  0.9998448148770804

In [172]:
pipe.predict_proba([['New Zealand','India','Mumbai',398,162,76,6,1.414,11.928]])

C:\Users\Ayush\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0.91, 0.09]])

In [173]:
# plt.barh(0,1,height=1,color='g')
# plt.barh(0,0.2,height=1,color='r')
# plt.xlim=(0,100)

In [174]:
pickle.dump(final_df,open('final_df.pkl','wb'))

In [175]:
over = 29.1
over_completed = int(str(over).split('.')[0])
balls = int(str(over).split('.')[1])
balls_thrown = (over_completed * 6) + balls
balls_rem = 300 - balls_thrown

In [176]:
pickle.dump(pipe,open('pipeline.pkl','wb'))

In [177]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 386635 entries, 384639 to 330682
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   batting_team       386635 non-null  object
 1   bowlling_team      386635 non-null  object
 2   city               386635 non-null  object
 3   target             386635 non-null  int64
 4   runs_require       386635 non-null  int64
 5   balls_remaining    386635 non-null  int32
 6   wickets_remaining  386635 non-null  int32
 7   crr                386635 non-null  float64
 8   rrr                386635 non-null  float64
 9   result             386635 non-null  int64
dtypes: float64(2), int32(2), int64(3), object(3)
memory usage: 29.5+ MB

In [178]:
import joblib

In [179]:
joblib.dump(pipe,'pipe.pkl')

['pipe.pkl']

In [180]:
pickle.dump(x_train,open('x_train.pkl','wb'))
pickle.dump(y_train,open('y_train.pkl','wb'))